### ISSUE TITLE
Debugging 500 Error on Luke's iMac

### ISSUE THREAD

**Issue by nelsonic** [FAC-GM/gm-magic#18]
Heroku Logs when attempting to `POST` to `/profile`

<img width="1722" alt="extension-500-error-heroku-log" src="https://cloud.githubusercontent.com/assets/194400/11119890/8236a484-8944-11e5-972f-98eb244b2d7d.png">

```sh
2015-11-12T13:45:48.128908+00:00 heroku[router]: at=info method=POST path="/profile" host=global-m.herokuapp.com request_id=cb07f346-9f24-4c19-8e28-480e72acad93 fwd="213.152.255.35" dyno=web.1 connect=1ms service=57ms status=500 bytes=356
2015-11-12T13:45:48.120891+00:00 app[web.1]: Debug: internal, implementation, error
2015-11-12T13:45:48.120896+00:00 app[web.1]:     Error: Uncaught error: RemoteTransportException[[kili-1][inet[/10.0.7.64:9300]][indices:data/write/index]]; nested: MapperParsingException[failed to parse [skills.level]]; nested: NumberFormatException[For input string: "99+"];
2015-11-12T13:45:48.120897+00:00 app[web.1]:     at respond (/app/node_modules/elasticsearch/src/lib/transport.js:260:15)
2015-11-12T13:45:48.120899+00:00 app[web.1]:     at checkRespForFailure (/app/node_modules/elasticsearch/src/lib/transport.js:219:7)
2015-11-12T13:45:48.120900+00:00 app[web.1]:     at HttpConnector.<anonymous> (/app/node_modules/elasticsearch/src/lib/connectors/http.js:155:7)
2015-11-12T13:45:48.120901+00:00 app[web.1]:     at IncomingMessage.wrapper (/app/node_modules/lodash/index.js:3095:19)
2015-11-12T13:45:48.120901+00:00 app[web.1]:     at emitNone (events.js:72:20)
2015-11-12T13:45:48.120902+00:00 app[web.1]:     at IncomingMessage.emit (events.js:166:7)
2015-11-12T13:45:48.120903+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:905:12)
2015-11-12T13:45:48.120904+00:00 app[web.1]:     at doNTCallback2 (node.js:450:9)
2015-11-12T13:45:48.120904+00:00 app[web.1]:     at process._tickDomainCallback (node.js:405:17)
2015-11-12T13:46:13+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.065 sample#load-avg-5m=0.08 sample#load-avg-15m=0.1 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15405660kB sample#memory-free=495632kB sample#memory-cached=12799732kB sample#memory-redis=13255456bytes sample#hit-rate=0.99956 sample#evicted-keys=0
2015-11-12T13:46:53+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.025 sample#load-avg-5m=0.065 sample#load-avg-15m=0.095 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15405660kB sample#memory-free=495616kB sample#memory-cached=12799764kB sample#memory-redis=13255456bytes sample#hit-rate=0.99956 sample#evicted-keys=0
2015-11-12T13:47:40+00:00 app[heroku-redis]: source=REDIS sample#active-connections=1 sample#load-avg-1m=0.03 sample#load-avg-5m=0.06 sample#load-avg-15m=0.095 sample#read-iops=0 sample#write-iops=0 sample#memory-total=15405660kB sample#memory-free=495468kB sample#memory-cached=12799796kB sample#memory-redis=13255456bytes sample#hit-rate=0.99956 sample#evicted-keys=0
```

**Comment by nelsonic** [comment]
Reading the `stack trace` its clear that this error is due to an ***invalid*** `type` because ES is expecting skill level to be `Number` and `99+` is *not* numeric ...

**Comment by iteles** [comment]
:+1: Fixed and deployed.
