### ISSUE TITLE
DOM error

### ISSUE THREAD

**Issue by heron2014** [FAC-GM/gm-magic#25]
Error in event handler for runtime.onMessage: TypeError: Cannot read property 'innerText' of undefined
at scrape (chrome-extension://ccgffoipijigdipijolokbjmolfohblm/js/scrape.js:11:68)
at chrome-extension://ccgffoipijigdipijolokbjmolfohblm/js/background.js:18:19

**Comment by heron2014** [comment]
Resolved [PR](https://github.com/FAC-GM/gm-magic/pull/39/)
